apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mc-server-manager
  namespace: {{ .Values.namespace.servers }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log", "pods/exec"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mc-server-manager-binding
  namespace: {{ .Values.namespace.servers }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mc-panel.fullname" . }}-backend
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: mc-server-manager
  apiGroup: rbac.authorization.k8s.io
