apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mc-panel.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
